### ISSUE TITLE
Documentation on filename formatting

### ISSUE THREAD

**Issue by 15532th** [HoloArchivists/TwcLazer#10]
Documentation on filename formatting options differs from actual state of the code in a few aspects.

Two formatting options for output file name described in help and README, namely `Hashtag` and `Pin Message`, are not present in `FileFormat_Translations`. `Category Name` value is taken from a field that doesn't exist in server response, and is effectively always `None`. None of them look like something that would be used in a stream recording filename to me, so the easiest fix would probably be removing them from the documentation.

`Category ID` currently gets movie id as value instead of category id. Since movie id is pretty useful as part of a filename, and some users could be using `%%Ci` for that, it would make sense to leave this option to be placeholder for movie id and update documentation to reflect that.

Currently, if more than one stream happens in a single day, both of them will have the same filename generated if default formatting options are used, which leads to both of them to be written in a single file. Solution to that might be adding movie id to default filename format the way yt-dlp does.

Both file name and chat formatting descriptions use single `%` to precede format placeholders, but formatting functions use `%%` instead, which is reflected in default format strings for both filename and chat format also using `%%`. Changing that might, again, break existing setups, so help could be updated to use it as well.

**Comment by ef1500** [comment]
I'll go ahead with removing them, as well as work on updating the formatting placeholders. 
> Both file name and chat formatting descriptions use single `%` to precede format placeholders, but formatting functions use `%%` instead, which is reflected in default format strings for both filename and chat format also using `%%`.

Currently, I've changed the code to use `$` as the prefix. Is that okay?

I have also added `movie_id` to the default filename. If that sounds good, let me know and I can commit it.

**Comment by 15532th** [comment]
Since `$` is a special character for variable expansion in Linux shells, it might become a bit more difficult to write scripts around program using it in arguments. On the other hand, `%%` is probably even worse in `bat` scripts. Picking a character that isn't special in any of commonly used shells might be a bit [problematic](https://streamlink.github.io/cli/tutorial.html#shell-syntax), so I would suggest sticking with `%`, since yt-dlp already [uses](https://github.com/yt-dlp/yt-dlp#output-template) it.

**Comment by ef1500** [comment]
I have addressed this and it should now be updated. Thank you very much for always taking the time out of your day to help improve my tools and suggest features like this. It really means a lot to me. 

I have added a [class](https://github.com/HoloArchivists/TwcLazer/blob/main/utils/ArgFormatter.py) called `ArgumentFormatter` which, for lack of a better term, aids with the formatting of the custom strings. It's basically a glorified version of the old  [strTranslate](https://github.com/HoloArchivists/TwcLazer/blob/e0dcfef73307198bcc92687ba4894a49aad32353/utils/ChatFormatter.py#L4-L11) method, and it allows you to add dictionaries of translations, either by name or just as a whole. You can then translate a string based upon the dictionary that you added to the class ([Usage Example 1](https://github.com/HoloArchivists/TwcLazer/blob/3adcc0ecc7f5a8a81248ec1651725b0158786388/utils/ChatFormatter.py#L40-L41), [Usage Example 2](https://github.com/HoloArchivists/TwcLazer/blob/3adcc0ecc7f5a8a81248ec1651725b0158786388/TwcLazer.py#L77-L88C24)).
Thought it was a neat little implementation that I could easily reuse in other projects.

Anyways, thanks again as always, cheers!
ef

**Comment by 15532th** [comment]
Perhaps default formatting arguments should use `%` instead of `%%` now and README should be updated to match `CLIhelper.py`?
[3adcc0e](https://github.com/HoloArchivists/TwcLazer/commit/3adcc0ecc7f5a8a81248ec1651725b0158786388) also breaks chat downloading, but it looks like a refactoring opportunity, so I would like to submit a patch for that myself.

**Comment by ef1500** [comment]
Of course, go for it
