### ISSUE TITLE
Timeout on websocket recv()

### ISSUE THREAD

**Issue by 15532th** [HoloArchivists/TwcLazer#5]
Timeout value of 2 seconds for ws.recv() [here](https://github.com/HoloArchivists/TwcLazer/blob/99060bd8313e42c0ae20363c309a4ac4240d8cf4/twitcasting/TwitcastWebsocket.py#L34) is probably too low.
While it's usually fast enough mid-download, the stream websocket seems to take a bit more time to respond right after establishing a connection. It causes a loop of continuous reconnects that can go for a few minutes before the server manages to respond fast enough from the start. What's worse, the server doesn't seem to expect a possibility of websocket being closed from client side, since a call to `ws.close()` after timeout takes 20 seconds, which is twice the default value of `close_timeout` argument of the [connect](https://websockets.readthedocs.io/en/stable/reference/asyncio/client.html#websockets.client.connect) method.

While this loop of reconnects might happen in the middle of a download, most often it's at the start, and once the program manages to get out of the loop, the rest usually goes without a problem. It seems to happen less often on audio-only streams, and more often on motion-heavy ones, such as videogames.

With all that, I suggest increasing the timeout to at least 20-30 seconds, since avoiding possible stuttering with a short timeout is not worth a guaranteed loss of 20 seconds of footage that follows. And in the worst case this repeats multiple times in a row. I've tested timeout values of 30 and 60 seconds, and it seems to fix the problem and otherwise work fine, except causing the program to take longer to stop on clean exit at the end of the stream, which should probably be acceptable.

**Comment by ef1500** [comment]
Thank you for letting me know!
I have increased the timeout to 25 seconds
